version: '3.4'

services:
  diplom:
    image: ${DOCKER_REGISTRY-}diplom
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    build:
      context: .
      dockerfile: diplom/Dockerfile
